=== tommyippoz/Multilayer_Monitor/AD_MultiLayer_Monitor_Master/model/configurationValidator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/configurationValidator" xmlns:tns="http://www.example.org/configurationValidator" elementFormDefault="qualified">




    <include schemaLocation=""></include>
    <complexType name="RequestDefinitionType">
    	<sequence minOccurs="1" maxOccurs="1">
    		<element name="url" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
            <element name="content" type="tns:RequestContentType" minOccurs="1" maxOccurs="1"></element>
            <element name="results"
    			type="tns:ResultsArrayDefinitionType" minOccurs="0"
    			maxOccurs="1">
    		</element>
        </sequence>
    	<attribute name="method" type="string" use="required"></attribute>
    	<attribute name="portlet" type="string" use="required"></attribute>
    </complexType>

    <complexType name="ResultDefinitionType">
    	<sequence>
    		<element name="Path" type="string" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="ResultsArrayDefinitionType">
    	<sequence>
    		<element name="result" type="tns:ResultDefinitionType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="IncludeType">
    	<attribute name="configuration-file" type="string" use="required"></attribute>
    </complexType>

    <complexType name="ConfigurationType">
	    <sequence maxOccurs="unbounded" minOccurs="0">
	    	<choice>
	    		<element name="Include" type="tns:IncludeType"></element>
	    		<element name="Request" type="tns:RequestDefinitionType"></element>
	    	</choice>
    	</sequence>
    </complexType>


    <complexType name="FunctionalTestType">
    	<sequence>
    		<element name="Configuration" type="tns:ConfigurationType"
    			minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="Workloads" type="tns:WorkloadsType"
    			minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="Run" type="tns:RunType" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="WorkloadDefinitionType">
    	<sequence>
    		<element name="Choreography" type="tns:CompoundStatments" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="RequestCallType">
    	<complexContent>
    		<extension base="tns:StatementType">
    			<sequence>
    				<element name="Parameters"
    					type="tns:RequestCallParametersType" minOccurs="0">
    				</element>
    				<element name="Results" type="tns:RequestCallResultsType" minOccurs="0"></element>
    			</sequence>
    			<attribute name="method" type="string" use="required"></attribute>
    			<attribute name="portlet" type="string"
    				use="required">
    			</attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="StoreResultType">
    	<attribute name="put-in" type="string" use="required"></attribute>
    	<attribute name="result-name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="StatementType"></complexType>

    <complexType name="CompoundStatments">
    	<complexContent>
    		<extension base="tns:StatementType">
    			<sequence>
    				<element name="Declarations"
    					type="tns:DeclareVariablesType" minOccurs="0">
    				</element>
    				<sequence minOccurs="0" maxOccurs="unbounded">
    					<choice>
    						<element name="Call"
    							type="tns:RequestCallType">
    						</element>
    						<element name="Cycle"
    							type="tns:CycleType">
    						</element>
    						<element name="Condition"
    							type="tns:ConditionalType">
    						</element>
    						<element name="Sleep"
    							type="tns:SleepType">
    						</element>
    						<element name="Parallel"
    							type="tns:ParallelType">
    						</element>
    					</choice>
    				</sequence>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="CycleType">
    	<complexContent>
    		<extension base="tns:CompoundStatments">
    			<attribute name="cycles" type="int" use="required"></attribute>
    			<attribute name="cycle-variable-name" type="string"
    				use="optional">
    			</attribute>
    			<attribute name="mode" use="required">
    				<simpleType>
    					<restriction base="string">
    						<enumeration value="seconds"></enumeration>
    						<enumeration value="times"></enumeration>
    					</restriction>
    				</simpleType>
    			</attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="ConditionalType">
    	<complexContent>
    		<extension base="tns:StatementType">
    			<sequence>
    				<element name="IfTrue"
    					type="tns:CompoundStatments" minOccurs="1" maxOccurs="1">
    				</element>
    				<element name="IfFalse" type="tns:CompoundStatments" minOccurs="0" maxOccurs="1"></element>
    			</sequence>
                <attribute name="variable" type="string" use="required">
    			</attribute>
                <attribute name="operator">
    				<simpleType>
    					<restriction base="string">
    						<enumeration value="&lt;"></enumeration>
    						<enumeration value="&gt;"></enumeration>
    						<enumeration value="="></enumeration>
    						<enumeration value="!="></enumeration>
    						<enumeration value="startsWith"></enumeration>
    						<enumeration value="endsWith"></enumeration>
    						<enumeration value="&lt;="></enumeration>
    						<enumeration value="&gt;="></enumeration>
    					</restriction>
    				</simpleType>
    			</attribute>
    			<attribute name="value" type="string"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <element name="FunctionalTest" type="tns:FunctionalTestType"></element>


    <complexType name="WorkloadsType">
    	<sequence minOccurs="0" maxOccurs="unbounded">
    		<choice>
	    		<element name="Include" type="tns:IncludeType"></element>
	    		<element name="Workload" type="tns:WorkloadDefinitionType"></element>
    		</choice>
    	</sequence>
    </complexType>



    <complexType name="RequestContentType">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="file" type="string" use="optional"></attribute>
    		</extension>
    	</simpleContent>
    </complexType>

    <complexType name="RunType">
    	<sequence>
            <element name="Declarations" type="tns:DeclareVariablesType" minOccurs="0" maxOccurs="1"></element>
            <element name="WorkloadReference"
    			type="tns:WorkloadReferenceType" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="WorkloadReferenceType">
		<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="ParameterType">
		<simpleContent>
			<extension base="string">
				<attribute name="name" type="string" use="required"></attribute>
				<attribute name="variable" type="string"></attribute>
			</extension>
		</simpleContent>
    </complexType>

    <complexType name="RequestCallParametersType">
    	<sequence>
    		<element name="Parameter" type="tns:ParameterType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="RequestCallResultsType">
    	<sequence>
    		<element name="StoreResult" type="tns:RequestCallStoreResultType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="RequestCallStoreResultType">
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="variable" type="string" use="required"></attribute>
    </complexType>

    <complexType name="DeclareVariableType">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="name" type="string" use="required"></attribute>
    		</extension>
    	</simpleContent>
    </complexType>

    <complexType name="DeclareVariablesType">
    	<sequence>
    		<element name="Declare" type="tns:DeclareVariableType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="SleepType">
    	<complexContent>
    		<extension base="tns:StatementType">
    			<attribute name="for" type="double" use="required"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="ParallelType">
    	<complexContent>
    		<extension base="tns:CompoundStatments">
    			<attribute name="numberOfThreads" type="int"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <attribute name="NewAttribute" type="string"></attribute>

</schema>

=== tommyippoz/Multilayer_Monitor/TestProject/workloads/Workload_Wiki.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:FunctionalTest xmlns:tns="http://www.example.org/configurationValidator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/configurationValidator ../model/configurationValidator.xsd ">
  <tns:Configuration><tns:Include
  		configuration-file="Portlet_Wiki_WikiNodeService.xml" /><tns:Include
  		configuration-file="Portal_UserService.xml" ></tns:Include><tns:Include
  		configuration-file="Portal_GroupService.xml" /><tns:Include
  		configuration-file="Portlet_Wiki_WikiPageService.xml" />
  </tns:Configuration>
  <tns:Workloads><!--Recupera le info di autenticazione-->
  	<tns:Workload name="getCredentials">
  		<tns:Choreography>
  			<tns:Call portlet="Portal_UserService" method="getUserById/1">
  				<tns:Parameters>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="companyId" name="companyId" /></tns:Results></tns:Call>
  			<tns:Call portlet="Portal_GroupService" method="getUserGroup/1">
  				<tns:Parameters>
  					<tns:Parameter name="companyId" variable="companyId"></tns:Parameter>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="groupId" name="groupId" /></tns:Results></tns:Call>
  		</tns:Choreography>
  	</tns:Workload>
  	<tns:Workload name="addNode">
  		<tns:Choreography>
  			<tns:Call portlet="Portlet_Wiki_WikiNodeService" method="addNode/1">
  				<tns:Parameters>
  					<tns:Parameter name="groupId" variable="groupId"></tns:Parameter>
  					<tns:Parameter name="name" variable="nameWikiNode"></tns:Parameter>
  					<tns:Parameter name="description">descrizione del nodo di prova</tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="nodeId" name="nodeId" /></tns:Results>
  			</tns:Call>
  		</tns:Choreography>
  	</tns:Workload>
  	<tns:Workload name="addPage">
  		<tns:Choreography>
  			<tns:Call portlet="Portlet_Wiki_WikiNodeService" method="getNode/2">
  				<tns:Parameters>
  					<tns:Parameter name="groupId" variable="groupId"></tns:Parameter>
  					<tns:Parameter name="name" variable="nameWikiNode"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="nodeId" name="nodeId" /></tns:Results>
  			</tns:Call>
  			<tns:Call portlet="Portlet_Wiki_WikiPageService" method="addPage/1">
  				<tns:Parameters>
  					<tns:Parameter name="nodeId" variable="nodeId">
  					</tns:Parameter>
  					<tns:Parameter name="title">
  						title Wiki
  					</tns:Parameter>
  					<tns:Parameter name="content">
  						content Wiki
  					</tns:Parameter>
  					<tns:Parameter name="summary">
  						summary Wiki
  					</tns:Parameter>
  				</tns:Parameters>
  			</tns:Call>
  		</tns:Choreography>
  	</tns:Workload>
  </tns:Workloads>
  <tns:Run>
  	<tns:Declarations>
  		<tns:Declare name="userId">184801</tns:Declare>
  		<tns:Declare name="companyId"></tns:Declare>
  		<tns:Declare name="groupId"></tns:Declare>
  		<tns:Declare name="nodeId"></tns:Declare>
  		<tns:Declare name="nameWikiNode">nodo di prova</tns:Declare></tns:Declarations>
  	<tns:WorkloadReference name="getCredentials" ></tns:WorkloadReference><tns:WorkloadReference
  		name="addPage" /></tns:Run>
</tns:FunctionalTest>

=== tommyippoz/Multilayer_Monitor/AD_MultiLayer_Monitor_Master/workloads/Workload_Users.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:FunctionalTest xmlns:tns="http://www.example.org/configurationValidator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/configurationValidator ../model/configurationValidator.xsd ">
  <tns:Configuration><tns:Include
  		configuration-file="Portal_UserService.xml" />
  </tns:Configuration>
  <tns:Workloads>
  	<tns:Workload name="getCredentials">
  		<tns:Choreography>
  			<tns:Call portlet="Portal_UserService" method="getUserById/1">
  				<tns:Parameters>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="companyId" name="companyId" /></tns:Results></tns:Call>
  			<tns:Call portlet="Portal_GroupService" method="getUserGroup/1">
  				<tns:Parameters>
  					<tns:Parameter name="companyId" variable="companyId"></tns:Parameter>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="groupId" name="groupId" /></tns:Results></tns:Call>
  		</tns:Choreography>
  	</tns:Workload>
  	<tns:Workload name="modifyUser">
  	
  		<tns:Choreography>
  			<tns:Call portlet="Portal_UserService" method="updatePassword/1">
  				<tns:Parameters>
  					<tns:Parameter name="password">provanuovaPassword</tns:Parameter>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters>
  			</tns:Call> 
  			  <tns:Call portlet="Portal_UserService" method="updateScreenName/1">
  				<tns:Parameters>
  					<tns:Parameter name="screenName">nuovohhhhhhhScreenName</tns:Parameter>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters>
  			</tns:Call>
  					
  			<tns:Call portlet="Portal_UserService" method="addOrganizationUsers/1">
  				<tns:Parameters>
  					<tns:Parameter name="organizationId"
  						variable="186627"></tns:Parameter>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters></tns:Call>
  		</tns:Choreography>
  	</tns:Workload>
  	
  </tns:Workloads>
  <tns:Run>
  	<tns:Declarations>
  		<tns:Declare name="companyId"></tns:Declare>
  		<tns:Declare name="userId"></tns:Declare>
	</tns:Declarations>
  	<tns:WorkloadReference name="modifyUser" ></tns:WorkloadReference></tns:Run>
</tns:FunctionalTest>

=== tommyippoz/Multilayer_Monitor/AD_MultiLayer_Monitor_Master/workloads/Workload_MB_MBThreadService.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:FunctionalTest xmlns:tns="http://www.example.org/configurationValidator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/configurationValidator ../model/configurationValidator.xsd ">
  <tns:Configuration>
  </tns:Configuration>
  <tns:Workloads>
  	<tns:Workload name="">
  		<tns:Choreography>
  			<tns:Call portlet="Portlet_MB_MBThreadService" method="getThreads/1">
  				<tns:Parameters>
  					<tns:Parameter name="groupId" variable="groupId"></tns:Parameter>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter>
  					<tns:Parameter name="status">0</tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="threadId" name="threadId" /></tns:Results>
  			</tns:Call>
  			<tns:Condition variable="userId" operator="!=" value="null">
  				<tns:IfTrue>
  				</tns:IfTrue>
  			</tns:Condition>
  		</tns:Choreography>
  	</tns:Workload>
  </tns:Workloads>
  <tns:Run/>
</tns:FunctionalTest>

=== tommyippoz/Multilayer_Monitor/AD_MultiLayer_Monitor_Master/workloads/configuration00.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:FunctionalTest xmlns:tns="http://www.example.org/configurationValidator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/configurationValidator ../model/configurationValidator.xsd ">
  <tns:Configuration>
	<tns:Request portlet="Wiki_Wiki" method="getPage">
    	<tns:url>http://192.168.2.151:8080/getPage</tns:url>
    	<tns:content><![CDATA[<xml>pippo</xml>]]></tns:content>
    	<tns:results>
    		<tns:result name="id">
    			<tns:Path>//Ciro/pippo/id</tns:Path>
    		</tns:result>
    		<tns:result name="nome">
    			<tns:Path>//Ciro/pippo/nome</tns:Path>
    		</tns:result>
    	</tns:results>
	</tns:Request>
	<tns:Request portlet="Wiki_Wiki" method="addPage">
    	<tns:url>http://192.168.2.151:8080/addPage</tns:url>
    	<tns:content><![CDATA[<xml>pippo2</xml>]]></tns:content>
    	<tns:results>
    		<tns:result name="id2">
    			<tns:Path>//Ciro/pippo/id2</tns:Path>
    		</tns:result>
    		<tns:result name="nome2">
    			<tns:Path>//Ciro/pippo/nome2</tns:Path>
    		</tns:result>
    	</tns:results>
	</tns:Request>
  </tns:Configuration>
  <tns:Workloads>
  	<tns:Workload name="ChangeWikiPage">
  		<tns:Choreography xsi:type="tns:CompoundStatments">
  			<tns:Call portlet="Wiki_Wiki" method="getPage" >
  				<tns:Parameters>
  					<tns:Parameter name="pippo" >23</tns:Parameter>
  				</tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="idPagina" name="id" /></tns:Results></tns:Call><tns:Cycle
  				cycles="2">
	<tns:Call portlet="Wiki_Wiki" method="addPage"></tns:Call>
</tns:Cycle>
  		</tns:Choreography>
  	</tns:Workload>
  </tns:Workloads>
  <tns:Run>
  	<tns:WorkloadReference name="ChangeWikiPage" /></tns:Run>
</tns:FunctionalTest>

=== tommyippoz/Multilayer_Monitor/AD_MultiLayer_Monitor_Master/workloads/Workload_Product.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:FunctionalTest xmlns:tns="http://www.example.org/configurationValidator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/configurationValidator ../model/configurationValidator.xsd ">
  <tns:Configuration><tns:Include
  		configuration-file="Portlet_SC_SCProductEntryService.xml" /><tns:Include
  		configuration-file="Portal_UserService.xml" ></tns:Include><tns:Include
  		configuration-file="Portal_GroupService.xml" /><tns:Include
  		configuration-file="Portlet_SC_SCProductVersionService.xml" /><tns:Include
  		configuration-file="Portlet_SC_SCLicenseService.xml" />
  </tns:Configuration>
  <tns:Workloads><!--Recupera le info di autenticazione-->
  	<tns:Workload name="getCredentials">
  		<tns:Choreography>
  			<tns:Call portlet="Portal_UserService" method="getUserById/1">
  				<tns:Parameters>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="companyId" name="companyId" /></tns:Results></tns:Call>
  			<tns:Call portlet="Portal_GroupService" method="getUserGroup/1">
  				<tns:Parameters>
  					<tns:Parameter name="companyId" variable="companyId"></tns:Parameter>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="groupId" name="groupId" /></tns:Results></tns:Call>
  		</tns:Choreography>
  	</tns:Workload><!--Inserisce un nuovo software al catalogo (preceduto da getCredentials)-->
  	<tns:Workload name="addProduct">
  		<tns:Choreography>
  			<tns:Call portlet="Portlet_SC_SCProductEntryService" method="addProductEntry/1">
  				<tns:Parameters>
  					<tns:Parameter name="groupId" variable="groupId"></tns:Parameter>
  					<tns:Parameter name="name">nome prodotto</tns:Parameter>
  					<tns:Parameter name="shortDescription">descrizione corta del prodotto</tns:Parameter>
  					<tns:Parameter name="longDescription">descrizione lunga del prodotto</tns:Parameter>
  					<tns:Parameter name="repoGroupId" variable="repoGroupId"></tns:Parameter>
  					<tns:Parameter name="repoArtifactId"
  						variable="repoArtifactId">
  					</tns:Parameter>
  					<tns:Parameter name="licenseId" variable="licenseId"></tns:Parameter>
  					<tns:Parameter name="author">me stesso</tns:Parameter>
  					<tns:Parameter name="pageURL">http://www.product.com</tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="productEntryId" name="productEntryId" /></tns:Results>
  			</tns:Call>
  		</tns:Choreography>
  	</tns:Workload><!--Inserisce un nuova versione al software (preceduto da getCredentials)-->
  	<tns:Workload name="addProductVersion">
  		<tns:Choreography>
  			<tns:Call portlet="Portlet_SC_SCProductVersionService" method="addProductVersion/1">
  				<tns:Parameters>
  					<tns:Parameter name="productEntryId"
  						variable="productEntryId">
  					</tns:Parameter>
  					<tns:Parameter name="version">2.5</tns:Parameter>
  					<tns:Parameter name="changeLog">cambiato il link al link</tns:Parameter>
  					<tns:Parameter name="downloadPageURL">http://www.urldidownload.com</tns:Parameter>
  					<tns:Parameter name="groupId" variable="groupId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="productVersionId" name="productVersionId" /></tns:Results></tns:Call>
  		</tns:Choreography>
  	</tns:Workload><!--Inserisce una nuova licenza e la associa ad un prodotto-->
  	<tns:Workload name="licenseAssign">
  		<tns:Choreography><!--Inserisco una nuova licenza-->
  			<tns:Call portlet="Portlet_SC_SCLicenseService" method="addLicense/1">
  				<tns:Parameters>
  					<tns:Parameter name="name">testLCS</tns:Parameter>
  					<tns:Parameter name="url">http://www.license.org</tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="licenseId" name="licenseId" /></tns:Results></tns:Call><!--Recupero il prodotto software-->
  			<tns:Call portlet="Portlet_SC_SCProductEntryService" method="getProductEntry/1">
  				<tns:Parameters>
  					<tns:Parameter name="productEntryId" variable="productEntryId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="name" name="name" />
  					<tns:StoreResult variable="shortDescription" name="shortDescription" />
  					<tns:StoreResult variable="longDescription" name="longDescription" />
  					<tns:StoreResult variable="pageURL" name="pageURL" />
  					<tns:StoreResult variable="author" name="author" />
  					<tns:StoreResult variable="repoGroupId" name="repoGroupId" />
  					<tns:StoreResult variable="repoArtifactId" name="repoArtifactId" /></tns:Results>
  			</tns:Call><!--Aggiorno l'id della licenza-->
  			<tns:Call portlet="Portlet_SC_SCProductEntryService" method="updateProductEntry/1">
  				<tns:Parameters>
  					<tns:Parameter name="productEntryId" variable="productEntryId"></tns:Parameter>
  					<tns:Parameter name="name" variable="name"></tns:Parameter>
  					<tns:Parameter name="shortDescription"
  						variable="shortDescription"></tns:Parameter>
  					<tns:Parameter name="longDescription"
  						variable="longDescription"></tns:Parameter>
  					<tns:Parameter name="pageURL" variable="pageURL"></tns:Parameter>
  					<tns:Parameter name="author" variable="author"></tns:Parameter>
  					<tns:Parameter name="repoGroupId" variable="repoGroupId"></tns:Parameter>
  					<tns:Parameter name="repoArtifactId" variable="repoArtifactId"></tns:Parameter>
  					<tns:Parameter name="licenseId" variable="licenseId"></tns:Parameter></tns:Parameters></tns:Call>
  		</tns:Choreography>
  	</tns:Workload>
  </tns:Workloads>
  <tns:Run>
  	<tns:Declarations>
  		<tns:Declare name="userId">184801</tns:Declare>
  		<tns:Declare name="companyId"></tns:Declare>
  		<tns:Declare name="groupId"></tns:Declare>
  		<tns:Declare name="productEntryId">188711</tns:Declare>
  		<tns:Declare name="repoGroupId"></tns:Declare>
  		<tns:Declare name="repoArtifactId"></tns:Declare>
  		<tns:Declare name="licenseId"></tns:Declare>
  		<tns:Declare name="name"></tns:Declare>
  		<tns:Declare name="shortDescription"></tns:Declare>
  		<tns:Declare name="longDescription"></tns:Declare>
  		<tns:Declare name="pageURL"></tns:Declare>
  		<tns:Declare name="author"></tns:Declare></tns:Declarations>
  	<tns:WorkloadReference name="getCredentials" ></tns:WorkloadReference>
	<tns:WorkloadReference name="licenseAssign" /></tns:Run>
</tns:FunctionalTest>

=== tommyippoz/Multilayer_Monitor/AD_MultiLayer_Monitor_Master/workloads/Workload_Category.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:FunctionalTest xmlns:tns="http://www.example.org/configurationValidator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/configurationValidator ../model/configurationValidator.xsd ">
  <tns:Configuration><tns:Include
  		configuration-file="Portal_UserService.xml" ></tns:Include><tns:Include
  		configuration-file="Portal_GroupService.xml" /><tns:Include
  		configuration-file="Portlet_MB_MBCategoryService.xml" />
  </tns:Configuration>
  <tns:Workloads><!--Recupera le info di autenticazione-->
  	<tns:Workload name="getCredentials">
  		<tns:Choreography>
  			<tns:Call portlet="Portal_UserService" method="getUserById/1">
  				<tns:Parameters>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="companyId" name="companyId" /></tns:Results></tns:Call>
  			<tns:Call portlet="Portal_GroupService" method="getUserGroup/1">
  				<tns:Parameters>
  					<tns:Parameter name="companyId" variable="companyId"></tns:Parameter>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="groupId" name="groupId" /></tns:Results></tns:Call>
  		</tns:Choreography>
  	</tns:Workload><!--Aggiungo una categoria - creo una sottocategoria-->
  	<tns:Workload name="addCategory">
  		<tns:Choreography>
  			<tns:Call portlet="Portlet_MB_MBCategoryService" method="addCategory/1">
  				<tns:Parameters>
  					<tns:Parameter name="catName" variable="catName"></tns:Parameter>
  					<tns:Parameter name="catDescr" variable="catDescr"></tns:Parameter>
  					<tns:Parameter name="groupId" variable="groupId"></tns:Parameter>
  					<tns:Parameter name="parentCategoryId">0</tns:Parameter>
  					<tns:Parameter name="keyattr">chiave attributo della categoria</tns:Parameter>
  					<tns:Parameter name="valattr">valore di attributo della categoria</tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="categoryId" name="categoryId" ></tns:StoreResult>
  				</tns:Results>
  			</tns:Call>
 			<tns:Call portlet="Portlet_MB_MBCategoryService" method="addCategory/1">
  				<tns:Parameters>
  					<tns:Parameter name="catName">sottoCategoria</tns:Parameter>
  					<tns:Parameter name="catDescr">sono una sottocategoria</tns:Parameter>
  					<tns:Parameter name="groupId" variable="groupId"></tns:Parameter>
  					<tns:Parameter name="parentCategoryId" variable="categoryId"></tns:Parameter>
  					<tns:Parameter name="keyattr">chiave attributo della sottocategoria</tns:Parameter>
  					<tns:Parameter name="valattr">valore di attributo della sottocategoria</tns:Parameter>
  				</tns:Parameters>
  			</tns:Call>  			
  		</tns:Choreography>
  	</tns:Workload>
  </tns:Workloads>
  <tns:Run>
  	<tns:Declarations>
  		<tns:Declare name="userId">184801</tns:Declare>
  		<tns:Declare name="companyId"></tns:Declare>
  		<tns:Declare name="groupId"></tns:Declare>
  		<tns:Declare name="catName">categoria di prova</tns:Declare>
  		<tns:Declare name="catDescr">descrizione di una categoria di prova</tns:Declare>
  		<tns:Declare name="categoryId"></tns:Declare></tns:Declarations>
  	<tns:WorkloadReference name="getCredentials" ></tns:WorkloadReference><tns:WorkloadReference name="addCategory" ></tns:WorkloadReference>
  	</tns:Run>
</tns:FunctionalTest>
