=== tommyippoz/Multilayer_Monitor/AD_MultiLayer_Monitor_Master/model/configurationValidator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/configurationValidator" xmlns:tns="http://www.example.org/configurationValidator" elementFormDefault="qualified">




    <include schemaLocation=""></include>
    <complexType name="RequestDefinitionType">
    	<sequence minOccurs="1" maxOccurs="1">
    		<element name="url" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
            <element name="content" type="tns:RequestContentType" minOccurs="1" maxOccurs="1"></element>
            <element name="results"
    			type="tns:ResultsArrayDefinitionType" minOccurs="0"
    			maxOccurs="1">
    		</element>
        </sequence>
    	<attribute name="method" type="string" use="required"></attribute>
    	<attribute name="portlet" type="string" use="required"></attribute>
    </complexType>

    <complexType name="ResultDefinitionType">
    	<sequence>
    		<element name="Path" type="string" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="ResultsArrayDefinitionType">
    	<sequence>
    		<element name="result" type="tns:ResultDefinitionType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="IncludeType">
    	<attribute name="configuration-file" type="string" use="required"></attribute>
    </complexType>

    <complexType name="ConfigurationType">
	    <sequence maxOccurs="unbounded" minOccurs="0">
	    	<choice>
	    		<element name="Include" type="tns:IncludeType"></element>
	    		<element name="Request" type="tns:RequestDefinitionType"></element>
	    	</choice>
    	</sequence>
    </complexType>


    <complexType name="FunctionalTestType">
    	<sequence>
    		<element name="Configuration" type="tns:ConfigurationType"
    			minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="Workloads" type="tns:WorkloadsType"
    			minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="Run" type="tns:RunType" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="WorkloadDefinitionType">
    	<sequence>
    		<element name="Choreography" type="tns:CompoundStatments" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="RequestCallType">
    	<complexContent>
    		<extension base="tns:StatementType">
    			<sequence>
    				<element name="Parameters"
    					type="tns:RequestCallParametersType" minOccurs="0">
    				</element>
    				<element name="Results" type="tns:RequestCallResultsType" minOccurs="0"></element>
    			</sequence>
    			<attribute name="method" type="string" use="required"></attribute>
    			<attribute name="portlet" type="string"
    				use="required">
    			</attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="StoreResultType">
    	<attribute name="put-in" type="string" use="required"></attribute>
    	<attribute name="result-name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="StatementType"></complexType>

    <complexType name="CompoundStatments">
    	<complexContent>
    		<extension base="tns:StatementType">
    			<sequence>
    				<element name="Declarations"
    					type="tns:DeclareVariablesType" minOccurs="0">
    				</element>
    				<sequence minOccurs="0" maxOccurs="unbounded">
    					<choice>
    						<element name="Call"
    							type="tns:RequestCallType">
    						</element>
    						<element name="Cycle"
    							type="tns:CycleType">
    						</element>
    						<element name="Condition"
    							type="tns:ConditionalType">
    						</element>
    						<element name="Sleep"
    							type="tns:SleepType">
    						</element>
    						<element name="Parallel"
    							type="tns:ParallelType">
    						</element>
    					</choice>
    				</sequence>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="CycleType">
    	<complexContent>
    		<extension base="tns:CompoundStatments">
    			<attribute name="cycles" type="int" use="required"></attribute>
    			<attribute name="cycle-variable-name" type="string"
    				use="optional">
    			</attribute>
    			<attribute name="mode" use="required">
    				<simpleType>
    					<restriction base="string">
    						<enumeration value="seconds"></enumeration>
    						<enumeration value="times"></enumeration>
    					</restriction>
    				</simpleType>
    			</attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="ConditionalType">
    	<complexContent>
    		<extension base="tns:StatementType">
    			<sequence>
    				<element name="IfTrue"
    					type="tns:CompoundStatments" minOccurs="1" maxOccurs="1">
    				</element>
    				<element name="IfFalse" type="tns:CompoundStatments" minOccurs="0" maxOccurs="1"></element>
    			</sequence>
                <attribute name="variable" type="string" use="required">
    			</attribute>
                <attribute name="operator">
    				<simpleType>
    					<restriction base="string">
    						<enumeration value="&lt;"></enumeration>
    						<enumeration value="&gt;"></enumeration>
    						<enumeration value="="></enumeration>
    						<enumeration value="!="></enumeration>
    						<enumeration value="startsWith"></enumeration>
    						<enumeration value="endsWith"></enumeration>
    						<enumeration value="&lt;="></enumeration>
    						<enumeration value="&gt;="></enumeration>
    					</restriction>
    				</simpleType>
    			</attribute>
    			<attribute name="value" type="string"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <element name="FunctionalTest" type="tns:FunctionalTestType"></element>


    <complexType name="WorkloadsType">
    	<sequence minOccurs="0" maxOccurs="unbounded">
    		<choice>
	    		<element name="Include" type="tns:IncludeType"></element>
	    		<element name="Workload" type="tns:WorkloadDefinitionType"></element>
    		</choice>
    	</sequence>
    </complexType>



    <complexType name="RequestContentType">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="file" type="string" use="optional"></attribute>
    		</extension>
    	</simpleContent>
    </complexType>

    <complexType name="RunType">
    	<sequence>
            <element name="Declarations" type="tns:DeclareVariablesType" minOccurs="0" maxOccurs="1"></element>
            <element name="WorkloadReference"
    			type="tns:WorkloadReferenceType" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="WorkloadReferenceType">
		<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="ParameterType">
		<simpleContent>
			<extension base="string">
				<attribute name="name" type="string" use="required"></attribute>
				<attribute name="variable" type="string"></attribute>
			</extension>
		</simpleContent>
    </complexType>

    <complexType name="RequestCallParametersType">
    	<sequence>
    		<element name="Parameter" type="tns:ParameterType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="RequestCallResultsType">
    	<sequence>
    		<element name="StoreResult" type="tns:RequestCallStoreResultType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="RequestCallStoreResultType">
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="variable" type="string" use="required"></attribute>
    </complexType>

    <complexType name="DeclareVariableType">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="name" type="string" use="required"></attribute>
    		</extension>
    	</simpleContent>
    </complexType>

    <complexType name="DeclareVariablesType">
    	<sequence>
    		<element name="Declare" type="tns:DeclareVariableType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="SleepType">
    	<complexContent>
    		<extension base="tns:StatementType">
    			<attribute name="for" type="double" use="required"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="ParallelType">
    	<complexContent>
    		<extension base="tns:CompoundStatments">
    			<attribute name="numberOfThreads" type="int"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <attribute name="NewAttribute" type="string"></attribute>

</schema>

=== tommyippoz/Multilayer_Monitor/TestProject/workloads/Workload_Tag.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:FunctionalTest xmlns:tns="http://www.example.org/configurationValidator"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/configurationValidator ../model/configurationValidator.xsd ">
	<tns:Configuration>
		<tns:Include configuration-file="Portlet_Asset_AssetTagService.xml" />
		<tns:Include configuration-file="Portal_UserService.xml" />
		<tns:Include configuration-file="Portal_GroupService.xml" />
	</tns:Configuration>
	<tns:Workloads><!--Recupera le info di autenticazione-->
	<tns:Workload name="getCredentials">
  		<tns:Choreography>
  			<tns:Call portlet="Portal_UserService" method="getUserById/1">
  				<tns:Parameters>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="companyId" name="companyId" /></tns:Results></tns:Call>
  			<tns:Call portlet="Portal_GroupService" method="getUserGroup/1">
  				<tns:Parameters>
  					<tns:Parameter name="companyId" variable="companyId"></tns:Parameter>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="groupId" name="groupId" /></tns:Results></tns:Call>
  		</tns:Choreography>
  		</tns:Workload><!--Recupera i tags-->
	<tns:Workload name="getTags">
		<tns:Choreography>
			<tns:Call portlet="Portlet_Asset_AssetTagService" method="getGroupsTags/1">
				<tns:Parameters>
					<tns:Parameter name="groupId" variable="groupId"></tns:Parameter></tns:Parameters>
				<tns:Results>
					<tns:StoreResult variable="tagId" name="tagId" /></tns:Results></tns:Call>
		</tns:Choreography>
	</tns:Workload><!--Aggiungo un tag-->
	<tns:Workload name="AddNewTag">
		<tns:Choreography>
			<tns:Call portlet="Portlet_Asset_AssetTagService" method="addTag/1">
				<tns:Parameters>
					<tns:Parameter name="nameTag">tag2Prova</tns:Parameter>
					<tns:Parameter name="groupId" variable="groupId">
					</tns:Parameter></tns:Parameters>
				<tns:Results>
					<tns:StoreResult variable="tagId" name="tagId" /></tns:Results></tns:Call>
		</tns:Choreography>
	</tns:Workload>
	</tns:Workloads>
	<tns:Run >
		<tns:Declarations>
			<tns:Declare name="userId">184801</tns:Declare>
			<tns:Declare name="groupId"></tns:Declare>
			<tns:Declare name="companyId"></tns:Declare>
			<tns:Declare name="eventId"></tns:Declare>
			<tns:Declare name="tagId"></tns:Declare></tns:Declarations>
		<tns:WorkloadReference name="getCredentials" /><tns:WorkloadReference
			name="AddNewTag" /></tns:Run>
</tns:FunctionalTest>

=== tommyippoz/Multilayer_Monitor/TestProject/workloads/Workload_MB_MBMessageService.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:FunctionalTest xmlns:tns="http://www.example.org/configurationValidator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/configurationValidator ../model/configurationValidator.xsd ">
  <tns:Configuration>
    <tns:Include configuration-file="Portlet_MB_MBMessageService.xml"></tns:Include>
    <tns:Include configuration-file="Portal_UserService.xml" ></tns:Include>
    <tns:Include configuration-file="Portlet_MB_MBCategoryService.xml" /><tns:Include
    	configuration-file="Portal_GroupService.xml" /><tns:Include
  		configuration-file="Portlet_MB_MBThreadService.xml" />
  </tns:Configuration>
  <tns:Workloads>
  	<tns:Workload name="getMBCategory">
  		<tns:Choreography>
  		<tns:Call portlet="Portal_UserService" method="getUserById/1">
  				<tns:Parameters>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="companyId" name="companyId" /></tns:Results></tns:Call><tns:Call portlet="Portal_GroupService" method="getUserGroup/1">
  				<tns:Parameters>
  					<tns:Parameter name="companyId" variable="companyId"></tns:Parameter>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="groupId" name="groupId" /></tns:Results></tns:Call><tns:Call portlet="Portlet_MB_MBCategoryService" method="getCategories/1">
  				<tns:Parameters>
  					<tns:Parameter name="groupId" variable="groupId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="mbCategoryId" name="mbCategoryId" /></tns:Results></tns:Call></tns:Choreography>
  	</tns:Workload><tns:Workload name="createForumThread">
  		<tns:Choreography>
  			<tns:Declarations>
  				<tns:Declare name="soggetto">Qui il soggetto del messaggio testing 2</tns:Declare>
  				<tns:Declare name="corpo">Qui il corpo del messaggio testing 2</tns:Declare></tns:Declarations>



  			<tns:Call portlet="Portlet_MB_MBMessageService" method="addMessage/1">
  				<tns:Parameters>
  					<tns:Parameter name="groupId" variable="groupId"></tns:Parameter>
  					<tns:Parameter name="mbCategoryId" variable="mbCategoryId"></tns:Parameter>
  					<tns:Parameter name="soggetto" variable="soggetto"></tns:Parameter>
  					<tns:Parameter name="corpo" variable="corpo"></tns:Parameter>
  				</tns:Parameters>
  			</tns:Call>
  		</tns:Choreography>
  	</tns:Workload>
  	<tns:Workload name="continueForumThread">
  		<tns:Choreography>
  			<tns:Declarations>
  				<tns:Declare name="userId" >184801</tns:Declare>
  				<tns:Declare name="companyId"></tns:Declare>
  				<tns:Declare name="groupId" ></tns:Declare>
  				<tns:Declare name="messageId" ></tns:Declare>
  				<tns:Declare name="threadId" ></tns:Declare>
  				<tns:Declare name="mbCategoryId" /></tns:Declarations>
  			<tns:Call portlet="Portal_UserService" method="getUserById/1">
  				<tns:Parameters>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="companyId" name="companyId" /></tns:Results></tns:Call>
  			<tns:Call portlet="Portal_GroupService" method="getUserGroup/1">
  				<tns:Parameters>
  					<tns:Parameter name="companyId" variable="companyId"></tns:Parameter>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="groupId" name="groupId" /></tns:Results></tns:Call>
  			<tns:Call portlet="Portlet_MB_MBCategoryService" method="getCategories/1">
  				<tns:Parameters>
  					<tns:Parameter name="groupId">0</tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="mbCategoryId" name="mbCategoryId" /></tns:Results></tns:Call>
  					
  			<tns:Call portlet="Portlet_MB_MBMessageService" method="addMessage/2">
  				<tns:Parameters>
  					<tns:Parameter name="groupId" variable="groupId" />
  					<tns:Parameter name="categoryId" variable="mbCategoryId" />
  				</tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="messageId" name="messageId" />
  					<tns:StoreResult variable="threadId" name="threadId" />
  				</tns:Results>
  			</tns:Call>

  			<tns:Call portlet="Portlet_MB_MBMessageService" method="addMessage/2">
  				<tns:Parameters>
  					<tns:Parameter name="groupId" variable="groupId"></tns:Parameter>
  					<tns:Parameter name="mbCategoryId" variable="mbCategoryId"></tns:Parameter>
  					<tns:Parameter name="messageId" variable="messageId"></tns:Parameter>
  					<tns:Parameter name="threadId" variable="threadId"></tns:Parameter>
  					<tns:Parameter name="soggetto">Qui il soggetto del messaggio</tns:Parameter>
  					<tns:Parameter name="corpo">
  						Qui il corpo del messaggio
  					</tns:Parameter></tns:Parameters></tns:Call>
  		</tns:Choreography>
  	</tns:Workload>
  	<tns:Workload name="deleteThread">
  		<tns:Choreography>
  			<tns:Call portlet="Portlet_MB_MBMessageService" method="getCategoryMessages/1">
  				<tns:Parameters>
  					<tns:Parameter name="groupId" variable="groupId"></tns:Parameter>
  					<tns:Parameter name="categoryId" variable="mbCategoryId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="messageId" name="messageId" /></tns:Results></tns:Call>
  			<tns:Call portlet="Portlet_MB_MBMessageService" method="deleteMessage/1">
  				<tns:Parameters>
  					<tns:Parameter name="messageId" variable="messageId"></tns:Parameter></tns:Parameters></tns:Call>
  		</tns:Choreography>
  	</tns:Workload>

  </tns:Workloads>
  <tns:Run>
			<tns:Declarations>
				<tns:Declare name="userId" >184801</tns:Declare>
				<tns:Declare name="companyId"></tns:Declare>
				<tns:Declare name="groupId" ></tns:Declare>
				<tns:Declare name="mbCategoryId" /><tns:Declare
					name="messageId"></tns:Declare>
			</tns:Declarations>
  	
  	<tns:WorkloadReference name="getMBCategory" ></tns:WorkloadReference><tns:WorkloadReference name="deleteThread" /></tns:Run>
</tns:FunctionalTest>

=== tommyippoz/Multilayer_Monitor/AD_MultiLayer_Monitor_Master/workloads/Workload_Poll.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:FunctionalTest xmlns:tns="http://www.example.org/configurationValidator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/configurationValidator ../model/configurationValidator.xsd ">
  <tns:Configuration><tns:Include
  		configuration-file="Portal_UserService.xml" ></tns:Include><tns:Include
  		configuration-file="Portal_GroupService.xml" /><tns:Include
  		configuration-file="Portlet_Polls_PollsQuestionService.xml" />
  </tns:Configuration>
  <tns:Workloads><!--Recupera le info di autenticazione-->
  	<tns:Workload name="getCredentials">
  		<tns:Choreography>
  			<tns:Call portlet="Portal_UserService" method="getUserById/1">
  				<tns:Parameters>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="companyId" name="companyId" /></tns:Results></tns:Call>
  			<tns:Call portlet="Portal_GroupService" method="getUserGroup/1">
  				<tns:Parameters>
  					<tns:Parameter name="companyId" variable="companyId"></tns:Parameter>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="groupId" name="groupId" /></tns:Results></tns:Call>
  		</tns:Choreography>
  	</tns:Workload><!--Aggiunge un Poll-->
  	<tns:Workload name="newPoll">
  		<tns:Choreography>
  			<tns:Call portlet="Portlet_Polls_PollsQuestionService" method="addQuestion/1">
  				<tns:Parameters>
  					<tns:Parameter name="titleMapLanguageId1">titoloEsempioLang</tns:Parameter>
  					<tns:Parameter name="titleMapValues1">titoloValueEsempio</tns:Parameter>
  					<tns:Parameter name="descriptionMapLanguageIds1">descriptionEsempioLan</tns:Parameter>
  					<tns:Parameter name="descriptionMapValues">descriptionValueEsempio</tns:Parameter>
  					<tns:Parameter name="groupId" variable="groupId"></tns:Parameter></tns:Parameters>
  			</tns:Call>  			
  		</tns:Choreography>
  	</tns:Workload>
  </tns:Workloads>
  <tns:Run>
  	<tns:Declarations>
  		<tns:Declare name="userId">10196</tns:Declare>
  		<tns:Declare name="companyId"></tns:Declare>
  		<tns:Declare name="groupId"></tns:Declare></tns:Declarations>

  	<tns:WorkloadReference name="getCredentials" ></tns:WorkloadReference>
	<tns:WorkloadReference name="newPoll" ></tns:WorkloadReference>
  	</tns:Run>
</tns:FunctionalTest>

=== tommyippoz/Multilayer_Monitor/TestProject/workloads/Workload_Calendar.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:FunctionalTest xmlns:tns="http://www.example.org/configurationValidator"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/configurationValidator ../model/configurationValidator.xsd ">
	<tns:Configuration>
		<tns:Include configuration-file="Portlet_Cal_CalEventService.xml" />
		<tns:Include configuration-file="Portal_UserService.xml" />
		<tns:Include configuration-file="Portal_GroupService.xml" />
	</tns:Configuration>
	<tns:Workloads><!--Recupera le info di autenticazione-->
	<tns:Workload name="getCredentials">
  		<tns:Choreography>
  			<tns:Call portlet="Portal_UserService" method="getUserById/1">
  				<tns:Parameters>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="companyId" name="companyId" /></tns:Results></tns:Call>
  			<tns:Call portlet="Portal_GroupService" method="getUserGroup/1">
  				<tns:Parameters>
  					<tns:Parameter name="companyId" variable="companyId"></tns:Parameter>
  					<tns:Parameter name="userId" variable="userId"></tns:Parameter></tns:Parameters>
  				<tns:Results>
  					<tns:StoreResult variable="groupId" name="groupId" /></tns:Results></tns:Call>
  		</tns:Choreography>
  		</tns:Workload><!--Inserisce un evento in calendario (preceduto da getCredentials)-->
	<tns:Workload name="addEventInCalendar">
		<tns:Choreography>
			<tns:Call portlet="Portlet_Cal_CalEventService" method="getEvents/1">
				<tns:Parameters>
					<tns:Parameter name="groupId" variable="groupId"></tns:Parameter>
					<tns:Parameter name="start">0</tns:Parameter>
					<tns:Parameter name="end">1392021312</tns:Parameter>
				</tns:Parameters>
			</tns:Call>
			<tns:Call portlet="Portlet_Cal_CalEventService" method="addEvent/1">
				<tns:Parameters>
					<tns:Parameter name="title">titoloEvento</tns:Parameter>
					<tns:Parameter name="description">descrizione evento</tns:Parameter>
					<tns:Parameter name="startDateMonth">10</tns:Parameter>
					<tns:Parameter name="startDateDay">10</tns:Parameter>
					<tns:Parameter name="startDateYear">2013</tns:Parameter>
					<tns:Parameter name="endDateMonth">10</tns:Parameter>
					<tns:Parameter name="endDateDay">10</tns:Parameter>
					<tns:Parameter name="endDateYear">2014</tns:Parameter>
					<tns:Parameter name="groupId" variable="groupId"></tns:Parameter></tns:Parameters>
				<tns:Results>
					<tns:StoreResult variable="eventId" name="eventId" /></tns:Results></tns:Call>
					
		</tns:Choreography>
	</tns:Workload><!--Elimina un evento in calendario (preceduto da getCredentials)-->
	<tns:Workload name="removeEventInCalendar">
		<tns:Choreography>
			<tns:Call portlet="Portlet_Cal_CalEventService" method="getEvents/1">
				<tns:Parameters>
					<tns:Parameter name="groupId" variable="groupId"></tns:Parameter>
					<tns:Parameter name="start">0</tns:Parameter>
					<tns:Parameter name="end">1</tns:Parameter></tns:Parameters>
				<tns:Results>
					<tns:StoreResult variable="eventId" name="eventId" /></tns:Results></tns:Call>
			<tns:Call portlet="Portlet_Cal_CalEventService" method="deleteEvent/1">
				<tns:Parameters>
					<tns:Parameter name="eventId" variable="eventId"></tns:Parameter></tns:Parameters></tns:Call>
		</tns:Choreography>
	</tns:Workload>
	</tns:Workloads>
	<tns:Run >
		<tns:Declarations>
			<tns:Declare name="userId">184801</tns:Declare>
			<tns:Declare name="groupId"></tns:Declare>
			<tns:Declare name="companyId"></tns:Declare>
			<tns:Declare name="eventId"></tns:Declare></tns:Declarations>
		<tns:WorkloadReference name="getCredentials" /><tns:WorkloadReference
			name="addEventInCalendar" /></tns:Run>
</tns:FunctionalTest>
